### ISSUE TITLE
remove technical variation function not working 

### ISSUE THREAD

**Issue by xiaosihao** [sritchie73/ukbnmr#2]
Hi,
As you can see from the screen shot, the extract and compute ratio function are all working fine. but the remove_technical_variation function is returning this: " Error in setnames(this_x, as.character(this_names$UKB.Field.ID), this_names$Biomarker) : Some duplicates exist in 'old': [23839] " message. Could you please let me know what went wrong and how to solve this problem? Many thanks
<img width="814" alt="WX20220506-105059@2x" src="https://user-images.githubusercontent.com/51140032/167109358-ad853f6b-7e2a-41c3-8f1f-4270a96b18ab.png">
.

**Comment by xiaosihao** [comment]
This is also happening to extract qc flags

**Comment by sritchie73** [comment]
Hi,

My first suspicion after revisiting the code is that your input data `ukb47736` is not in a format my code is expecting.

Can you print out and show me some of the column names of your data? E.g. `names(ukb47736)[1:20]`

**Comment by xiaosihao** [comment]
> 

<img width="938" alt="image" src="https://user-images.githubusercontent.com/51140032/167116693-513c0c10-3089-4e5d-abe0-14cbfbd2f153.png">
The data is directly from ukbiobank

**Comment by sritchie73** [comment]
Hmm that looks correct - this may be tricky to track down.

Looking at your first screenshot, am I right that `extract_biomarkers()` and `compute_nightingale_ratios()` ran without error, and the error happens when you run `remove_technical_variation()`?

You mention the error also occurs when extracting the QC flags. There's two functions that do this (both also used in `remove_technical_variation()`.  Can you check which of `extract_sample_qc_flags()` and `extract_biomarker_qc_flags()` is giving you the error?

**Comment by sritchie73** [comment]
A few possibilities of what might be happening here:

(1) UK Biobank have subtly changed the output or fields available in such a way that breaks the existing code. 

(2) Some of the QC fields my package looks for are missing from your data, and the code I've written to handle these cases doesn't work like I expected.

(3) Somehow the way you've extracted data, or the data that UKB has provided you, has duplicate columns, which is causing my the package to error.

Unfortunately I can't test any of these cases directly as I don't (and can't) have access to your data, so it will take some back and forth to debug the issue (for what its worth the package runs on the extracted UK Biobank data I currently have access to).

**Comment by sritchie73** [comment]
A potential way you might try bypassing whatever is causing the issue:

The package is also designed to handle UKB data that's been processed by the `ukbtools` R package (https://cran.r-project.org/web/packages/ukbtools/index.html), so you could try running that first on your data before passing it to the ukbnmr package.

**Comment by xiaosihao** [comment]
> extract_sample_qc_flags()

Thanks for your reply. Only extract_biomarker_qc_flags() is returning error message. extract_sample_qc_flags works fine.
<img width="802" alt="image" src="https://user-images.githubusercontent.com/51140032/167317437-ee60012d-0cc4-48fd-989c-a7618d035d80.png">

**Comment by xiaosihao** [comment]
> A potential way you might try bypassing whatever is causing the issue:
> 
> The package is also designed to handle UKB data that's been processed by the `ukbtools` R package (https://cran.r-project.org/web/packages/ukbtools/index.html), so you could try running that first on your data before passing it to the ukbnmr package.

Sorry, may I ask which function of the ukbtools should I use before passing to the ukbnmr package?

**Comment by sritchie73** [comment]
The `ukb_df` function in the `ukbtools` package, following just the first part of the ukbtools tutorial, "Making a dataset": https://cran.r-project.org/web/packages/ukbtools/vignettes/explore-ukb-data.html

**Comment by sritchie73** [comment]
Ok, I think I may have isolated the issue:

Does your data have either a `f.23839.0.0` or `f.23839.1.0` column in it, and if it does, can you check whether these columns have any data in them, or whether they're entirely empty?

In my version of the extracted data, these columns don't exist, as the field itself has no data in it (and this is what's also still reported in the UK Biobank showcase: https://biobank.ndph.ox.ac.uk/showcase/field.cgi?id=23839), so the package has hard-coded these QC fields to add in, which will cause the duplicate error if these fields already exist in your data.

**Comment by xiaosihao** [comment]
> Ok, I think I may have isolated the issue:
> 
> Does your data have either a `f.23839.0.0` or `f.23839.1.0` column in it, and if it does, can you check whether these columns have any data in them, or whether they're entirely empty?
> 
> In my version of the extracted data, these columns don't exist, as the field itself has no data in it (and this is what's also still reported in the UK Biobank showcase: https://biobank.ndph.ox.ac.uk/showcase/field.cgi?id=23839), so the package has hard-coded these QC fields to add in, which will cause the duplicate error if these fields already exist in your data.

Hi, I've checked those two columns are not in my dataset. By the way, there are 510 data fields in my dataset. I am checking with my colleague if the data contains biomarker qc information at all as only extrac_biomarker_qc function has failed.

**Comment by sritchie73** [comment]
I've just pushed an update.

Can you run `remotes::install_github("sritchie/ukbnmr")` and test whether `extract_biomarker_qc_flags()` still gives you an error?

If it does, I've also added the option to skip the biomarker QC flag extraction and collation in `remove_technical_variation()` as those QC flags aren't strictly needed. You can run this as `remove_technical_variation(ukb47736, skip.biomarker.qc.flags=TRUE)`

**Comment by xiaosihao** [comment]
> remotes::install_github("sritchie/ukbnmr")

The extract_biomarker_qc_flags() is working now. However, the remove_technical_variation() is still missing some data fields (see screenshots). I am requesting this data from my colleague now. Hope this will do the job. Thanks a lot. I will keep you updated.
<img width="1071" alt="image" src="https://user-images.githubusercontent.com/51140032/167503483-332811dd-2f83-4b39-968e-da32a0045cb3.png">

**Comment by sritchie73** [comment]
Glad to hear that `extract_biomarker_qc_flags()` is now working.

`remove_technical_variation()` does need those particular fields for the procedure, so if they're not present in your data (e.g. as f.23658.0.0 etc) then you won't be able to run it. 

These are fields that UK Biobank made available after the initial NMR data release, at our request based on our findings/package. I'm not sure if these fields were made automatically available to applications that requested the NMR data, so you may need to request these, request a data refresh, and redownload your UK Biobank data.
